Updated docker-publish.yml in main branch

diff --git a/docker-publish.yml b/docker-publish.yml
--- a/docker-publish.yml
+++ b/docker-publish.yml
@@ -2,7 +2,7 @@ name: Docker Image CI
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "**" ]
 
 jobs:
   build:
@@ -13,10 +13,32 @@ jobs:
       # This action copies your repository files (including the Dockerfile) to the runner
       uses: actions/checkout@v4
 
+    - name: Log in to Docker Hub (Optional, if pushing to a registry)
+      if: github.ref == 'refs/heads/main'
+      uses: docker/login-action@v3
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_TOKEN }}
+
+    - name: Get short commit SHA
+      id: slug
+      run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
+
     - name: Build and push Docker image
       # This action builds the image from your Dockerfile on the runner
       uses: docker/build-push-action@v6
       with:
         context: .
-        push: false # Set to true to push to registry, false to build locally for testing
-        tags: telephone-book:latest
+        load: true
+        push: ${{ github.ref == 'refs/heads/main' }}
+        tags: | # Set to true to push to registry, false to build locally for testing
+          ${{ secrets.DOCKER_USERNAME }}/telephone-book:latest
+          ${{ secrets.DOCKER_USERNAME }}/telephone-book:${{ steps.slug.outputs.short_sha }}
+
+    - name: Verify image exists locally
+      run: |
+        docker images
+        # We can also check for our specific image name
+        docker image inspect ${{ secrets.DOCKER_USERNAME }}/telephone-book:latest || echo "Image not found!"
+
+
