Fix: Added buildx module to the code as suggested by earlier build

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -26,6 +26,11 @@ jobs:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
 
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v3
+      with:
+        driver: docker-container # Forces the use of a containerized builder for better compatibility
+
     - name: Get short commit SHA
       id: slug
       run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
@@ -43,15 +48,15 @@ jobs:
 
     - name: Verify image exists locally
       run: |
-        docker images
+        sudo docker images
         # We can also check for our specific image name
-        docker image inspect ${{ secrets.DOCKER_USERNAME }}/telephone-book:latest || echo "Image not found!"
+        sudo docker image inspect ${{ secrets.DOCKER_USERNAME }}/telephone-book:latest || echo "Image not found!"
 
     - name: Build and Start Containers
       run: |
-        docker compose down && docker compose up -d --build --force-recreate --pull always
+        sudo docker compose down && sudo docker compose up -d --build --force-recreate --pull always
 
     - name: Verify Deployment
       run: |
-        docker compose ps
-        docker ps -a
+        sudo docker compose ps
+        sudo docker ps -a
