Updated docker-publish file for Task-6

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -2,12 +2,11 @@ name: Docker Image CI
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "**" ]
 
 jobs:
   build:
-    runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/main'
+    runs-on: self-hosted
 
     steps:
     - name: Checkout source code
@@ -15,6 +14,7 @@ jobs:
       uses: actions/checkout@v4
 
     - name: Log in to Docker Hub (Optional, if pushing to a registry)
+      if: github.ref == 'refs/heads/main'
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
@@ -29,7 +29,23 @@ jobs:
       uses: docker/build-push-action@v6
       with:
         context: .
-        push: true
+        load: true
+        push: ${{ github.ref == 'refs/heads/main' }}
         tags: | # Set to true to push to registry, false to build locally for testing
           ${{ secrets.DOCKER_USERNAME }}/telephone-book:latest
           ${{ secrets.DOCKER_USERNAME }}/telephone-book:${{ steps.slug.outputs.short_sha }}
+
+    - name: Verify image exists locally
+      run: |
+        docker images
+        # We can also check for our specific image name
+        docker image inspect ${{ secrets.DOCKER_USERNAME }}/telephone-book:latest || echo "Image not found!"
+
+    - name: Build and Start Containers
+      run: |
+        docker compose down && docker compose up -d --build --force-recreate --pull always
+
+    - name: Verify Deployment
+      run: |
+        docker compose ps
+        docker ps -a
